{% set name = "wassima" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wassima-{{ version }}.tar.gz
  sha256: 9d0dd4d7f8cdc1247518daf72b656f77f87a870861aeda73e32a43e583202ae6

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.6.0,<2
    - pip
  run:
    - python >={{ python_min }}


test:
  imports:
    - wassima
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jawah/wassima
  summary: Access your OS root certificates with the atmost ease
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
