{% set name = "wassima" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wassima-{{ version }}.tar.gz
  sha256: 9d0dd4d7f8cdc1247518daf72b656f77f87a870861aeda73e32a43e583202ae6

build:
  skip: true  # [py<37]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}

    - cargo-bundle-licenses  # To bundle cargo licenses
  host:
    - python
    - maturin >=1.2,<2.0
    - pip
  run:
    - python


test:
  imports:
    - wassima
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jawah/wassima
  summary: Access your OS root certificates with the atmost ease
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
